hours_report_environment: &hours_report_environment
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['HOURS_REPORT_DB_USER'] %>
  password: <%= ENV['HOURS_REPORT_DB_PASSWORD'] %>
  host: <%= ENV['HOURS_REPORT_DB_HOST'] %>
  port: <%= ENV['HOURS_REPORT_DB_PORT'] %>

development:
  database: hours_report_development
  <<: *hours_report_environment

test:
  database: hours_report_test
  <<: *hours_report_environment

production:
  <<: *hours_report_environment
  database: rails
