development:
  adapter: postgresql
  encoding: unicode
  database: hours_report_development
  host: localhost
  pool: 5
  username: danevron
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hours_report_test
  host: localhost
  pool: 5
  username: danevron
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
